services:
  - type: web
    name: nlp-ticket-classifier
    env: python
    pythonVersion: 3.10
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
